name: libasserest_interface
description: Interface for implementing asserest's on different protocols.
repository: https://github.com/Asserest/libasserest_interface
version: '1.0.0'
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  async_task: ^1.0.20
  yaml: ^3.1.2
  meta: ^1.9.1
dev_dependencies:
  test: ^1.24.2