name: libasserest_interface
description: Interface for implementing asserest's on different protocols.
repository: https://github.com/Asserest/libasserest_interface
version: '1.0.0'
environment:
  sdk: '>2.18.999 <4.0.0'
dependencies:
  meta: ^1.8.0
  quiver: ^3.2.1
  async_task: ^1.0.20
platforms:
  linux:
  macos:
  windows:
  android:
  ios:
